server:
  port: 8080
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
    org.springframework.security: DEBUG


employees:
  backend-url: http://localhost:8081

spring:
  application:
    name: employees-frontend

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: employees-frontend
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8084/login/oauth2/code/
            scope: openid,email,profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/auth/realms/EmployeesRealm

