server:
  port: 9000
  servlet:
    session:
      cookie:
        name: ASSESSIONID

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              #              client-secret: "$2a$10$cJ/2l6es3GMEgyO41dcNd.QLTFSiNsV.onRGi1Py01KU/9qgumVuG"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://localhost:8080/"
              scopes:
                - "openid"
                - "profile"
                - "employees:read"
                - "employees:write"
            require-authorization-consent: true